### PR TITLE
SDAP-214 Simplify EDGE directory structure

### PR DESCRIPTION
**Pull request by lewismc**
@ntquach @fgreg this addresses https://issues.apache.org/jira/browse/SDAP-214

### CODE REVIEW

**Comment by lewismc** [comment]
Any comments?

**Comment by rawkintrevo** [comment]
It appears you also upgraded a couple of things to python3.  

That's OK, but in general its better to make another PR for something like `SDAP-XXX Upgrade Edge directory to python3` or whatever. It just makes it easier to track changes if someone ever needs to go through it. 

just my .02

**Comment by fgreg** [comment]
Seems reasonable to me. @lewismc Were you able to successfully start it locally using the instructions from the Readme?

**Comment by lewismc** [comment]
@rawkintrevo thanks for reviewinbg

> It appears you also upgraded a couple of things to python3....

Negative, that work was done in https://github.com/apache/incubator-sdap-edge/pull/9, the only Python3 'stuff' on this branch was documentation int he README.

**Comment by lewismc** [comment]
@fgreg 

> Were you able to successfully start it locally using the instructions from the Readme?

Yes
```
lmcgibbn@MT-207576 ~/Downloads/incubator-sdap-edge(SDAP-214) $ pip3 install -r requirements.txt
Requirement already satisfied: tornado==4.2.1 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (4.2.1)
Requirement already satisfied: jinja2==2.8 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (2.8)
Requirement already satisfied: python-dateutil==2.4.1 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 3)) (2.4.1)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python3.7/site-packages (from jinja2==2.8->-r requirements.txt (line 2)) (0.23)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil==2.4.1->-r requirements.txt (line 3)) (1.10.0)
lmcgibbn@MT-207576 ~/Downloads/incubator-sdap-edge(SDAP-214) $ source edge-env.bash
lmcgibbn@MT-207576 ~/Downloads/incubator-sdap-edge(SDAP-214) $ python3 server.py
2019-12-02 13:40:47,171 - root - INFO - tornado is started.
```

**Review by fgreg — APPROVED** [review]

**Comment by rawkintrevo** [comment]
@lewismc  Ahh my bad, I was looking at the lines, not the context (e.g. the file that was being edited).

**Pull request merged**
