### PR TITLE
SDAP-212 Update EDGE to Python 3.7

### PR DESCRIPTION
**Pull request by lewismc**
Bulk result of running Python's 2to3-3.7 tooling on the codebase.
This issue addresses https://issues.apache.org/jira/browse/SDAP-212

### CODE REVIEW

**Comment by lewismc** [comment]
Also, it occurred to me that the build system for EDGE doesn't make much sense...
I'm thinking about removing the  pom.xml and then just moving everything under [main](https://github.com/apache/incubator-sdap-edge/tree/master/src/main) to the top level.
Everything under [site](https://github.com/apache/incubator-sdap-edge/tree/master/src/site) can be moved to a wiki.
Any thoughts?

**Comment by ntquach** [comment]
The suggested changes make sense. Thanks Lewis.

**Comment by fgreg** [comment]
> Also, it occurred to me that the build system for EDGE doesn't make much sense...
> I'm thinking about removing the pom.xml and then just moving everything under [main](https://github.com/apache/incubator-sdap-edge/tree/master/src/main) to the top level.
> Everything under [site](https://github.com/apache/incubator-sdap-edge/tree/master/src/site) can be moved to a wiki.
> Any thoughts?

@lewismc I think you're probably right. I'd move this discussion over to the mailing list or open a new JIRA for it as I think input from Nga would be appreciated (I'm not sure if anything under site is relevant anymore).

**Comment by lewismc** [comment]
@ntquach @fgreg thanks for input. The new ticket for the directory structure is created as https://issues.apache.org/jira/browse/SDAP-214

**Pull request merged**
